
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: myapi_db
      MYSQL_ROOT_PASSWORD: kapila@123
      MYSQL_USER: springuser
      MYSQL_PASSWORD: Spring@123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysqldm

  springboot-app:
    build: .
    container_name: myapi
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapi_db
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: Spring@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:











